import { CONSTANTS } from "../../constants";
import type { FormField } from "../../layouts/types/form";

export const adminSearchConfig: FormField[] = [
    {
        type: 'text',
        name: 'userId',
        label: 'User ID',
        placeholder: 'Enter User Id',
        grid: 3,
    },
    {
        type: 'text',
        name: 'userName',
        label: 'User Name',
        placeholder: 'Enter user name',
        grid: 3,
    },
    {
        type: 'select',
        name: CONSTANTS.Key_COMPANY_NAME,
        label: CONSTANTS.Key_COMPANY_NAME,
        options: [],
        grid: 3,
    },
];

export const newUserRegistrationFields: FormField[] = [
    {
        type: 'autocomplete',
        name: 'companyId',
        label: 'Company',
        placeholder: 'Select Company',
        options: [],
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'employeeId',
        label: 'Employee ID',
        placeholder: 'Enter employee ID',
        grid: 6,
    },
    {
        type: 'text',
        name: 'firstName',
        label: 'First Name',
        placeholder: 'Enter first name',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'lastName',
        label: 'Last Name',
        placeholder: 'Enter last name',
        grid: 6,
    },
    {
        type: 'text',
        name: 'userName',
        label: 'Username',
        placeholder: 'Enter username',
        required: true,
        grid: 6,
    },
    {
        type: 'password',
        name: 'password',
        label: 'Password',
        placeholder: 'Enter password',
        required: true,
        grid: 6,
    },
    {
        type: 'password',
        name: 'confirmPassword',
        label: 'Confirm Password',
        placeholder: 'Confirm password',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'email',
        label: 'Email',
        placeholder: 'Enter email address',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'mobile',
        label: 'Mobile Number',
        placeholder: 'Enter mobile number',
        required: true,
        grid: 6,
    },
    {
        type: 'autocomplete',
        name: 'roleId',
        label: 'Role',
        placeholder: 'Select Role',
        options: [],
        required: true,
        grid: 6,
    },
    {
        type: 'switch',
        name: 'isActive',
        label: 'Active',
        grid: 6,
    },
];


export const newCompanyRegistrationFields: FormField[] = [
    {
        type: 'text',
        name: 'companyCode',
        label: 'Company Code',
        placeholder: 'Enter company code',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'companyName',
        label: 'Company Name',
        placeholder: 'Enter company name',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'contactPerson',
        label: 'Contact Person',
        placeholder: 'Enter contact person',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'mobile',
        label: 'Mobile Number',
        placeholder: 'Enter mobile number',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'email',
        label: 'Email Address',
        placeholder: 'Enter email address',
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'website',
        label: 'Website',
        placeholder: 'https://www.example.com',
        grid: 6,
    },
    {
        type: 'text',
        name: 'gstNumber',
        label: 'GST Number',
        placeholder: 'Enter GST number',
        grid: 6,
    },
    {
        type: 'text',
        name: 'panNumber',
        label: 'PAN Number',
        placeholder: 'Enter PAN number',
        grid: 6,
    },
    {
        type: 'text',
        name: CONSTANTS.KEY_ADDRESS,
        label: CONSTANTS.LBL_ADDRESS,
        placeholder: 'Enter address',
        grid: 12,
    },
    {
        type: 'autocomplete',
        name: CONSTANTS.KEY_CITY,
        label: CONSTANTS.LBL_CITY,
        options: [],
        required: true,
        grid: 6,
    },
    {
        type: 'text',
        name: 'state',
        label: 'State',
        placeholder: 'Enter state',
        grid: 6,
    },
    {
        type: 'text',
        name: 'country',
        label: 'Country',
        placeholder: 'Enter country',
        grid: 6,
    },
    {
        type: 'text',
        name: 'pincode',
        label: 'Pincode',
        placeholder: 'Enter pincode',
        grid: 6,
    },
    {
        type: 'switch',
        name: 'isActive',
        label: 'Active',
        grid: 6,
    },
];